- name: Install generic dependencies on development VM
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - git
    - createrepo
    - tree
    - lynx

- name: Download Android repo tool
  get_url:
    url: "https://storage.googleapis.com/git-repo-downloads/repo"
    dest: "/usr/bin/repo"
    mode: 0655

