- name: Install and run docker on VM
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
  notify:
    - Start docker
  become: yes
  become_user: root

- name: Start uhttpd container
  docker:
    name: mydata
    image: fnichol/uhttpd
    state: present
    expose:
    - 8080
    volumes:
    - /data
  become: yes
  become_user: root

